### ISSUE TITLE
Home assistant

### ISSUE THREAD

**Issue by gieljnssns** [EnergyID/smappy#1]
Can you integrate this in https://home-assistant.io ?

**Comment by JrtPec** [comment]
I'm not familiar with Home Assistant, but I took a quick look and it seems like the platform should be able to integrate a service like this fairly easily. So I'd recommend posting an issue on https://github.com/home-assistant/home-assistant, and ask them what it would take to support Smappee.  I recon this package would be perfectly suitable to build an interface with.

If there is something I could do from this side (like implementing the actuators, or making the code more suitable for implementation), I'm very happy to help!

**Comment by gieljnssns** [comment]
> Op 3 mei 2016, om 00:09 heeft Jan Pecinovsky <notifications@github.com> het volgende geschreven:
> 
> I'm not familiar with Home Assistant, but I took a quick look and it seems like the platform should be able to integrate a service like this fairly easily. So I'd recommend posting an issue on https://github.com/home-assistant/home-assistant <https://github.com/home-assistant/home-assistant>, and ask them what it would take to support Smappee. I recon this package would be perfectly suitable to build an interface with.
> 
> If there is something I could do from this side (like implementing the actuators, or making the code more suitable for implementation), I'm very happy to help!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/EnergyID/smappy/issues/1#issuecomment-216380288>
Kan het zijn dat jij gewoon nederlands verstaat?
Ik heb het daar al eens gevraagd, geen reactie.
Ik kan wel m’n smart plugs gebruiken met het maker channel van ifttt, maar ik zou graag het stroomverbruik ook nog kunnen monitoren.
Ik ben zelf ook een beetje phyton aan het leren, maar ben zelf nog met iets anders bezig, hierna wil ik zelf wel eens proberen.

Giel

**Comment by JrtPec** [comment]
Binnen een maandje of zo kan ga je je Smappee kunnen koppelen aan EnergieID.be, dus dan kan je daar evt. je verbruik al opvolgen ;-) We rapporteren wel enkel op maandbasis, dus als je meer details wilt, zal je inderdaad misschien zelf aan de slag moeten...
Home Assistant lijkt me wel een tof project, maar ik heb zelf geen Smappee om mee te testen dus ik ben bang dat ik je niet veel kan helpen.

Veel succes!

**Comment by gieljnssns** [comment]
Ik ben dan toch maar eens een poging aan het doen,

Dit is het eerste stuk van mijn smappee.py file:


import logging
import socket
from urllib.error import URLError
from datetime import timedelta

from homeassistant.const import (
CONF_ACCESS_TOKEN, CONF_NAME, CONF_API_KEY, CONF_PASSWORD,
CONF_USERNAME, STATE_UNKNOWN)
from homeassistant.helpers.entity import Entity
from homeassistant.util import Throttle

_LOGGER = logging.getLogger(__name__)

REQUIREMENTS = [
    'https://github.com/EnergyID/smappy/archive/master.zip'
    '#smappee/smappee==0.1.1']
Enn bij het installeren krijgt mijn raspberry pi deze fouten:


16-05-03 12:54:45 INFO (MainThread) [homeassistant.loader] Loaded sensor.smappee from homeassistant.components.sensor.smappee
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1137, in parseString
    raise exc
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1127, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1001, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 2412, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1005, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 2215, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 5), (line:1, col:6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2788, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'://githu'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/util/package.py", line 46, in check_package_exists
    req = pkg_resources.Requirement.parse(package)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2833, in parse
    req, = parse_requirements(s)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2781, in parse_requirements
    yield Requirement(line)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2790, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'://githu'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1137, in parseString
    raise exc
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1127, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1001, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 2412, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1005, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/pyparsing.py", line 2215, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 7), (line:1, col:8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2788, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'/smappee'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/__main__.py", line 245, in setup_and_run_hass
    skip_pip=args.skip_pip, log_rotate_days=args.log_rotate_days)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/bootstrap.py", line 303, in from_config_file
    skip_pip=skip_pip)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/bootstrap.py", line 275, in from_config_dict
    _setup_component(hass, domain, config)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/bootstrap.py", line 128, in _setup_component
    p_name)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/bootstrap.py", line 206, in prepare_setup_platform
    if not _handle_requirements(hass, platform, platform_path):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/bootstrap.py", line 68, in _handle_requirements
    if not pkg_util.install_package(req, target=hass.config.path('deps')):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/util/package.py", line 22, in install_package
    if check_package_exists(package, target):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/util/package.py", line 49, in check_package_exists
    req = pkg_resources.Requirement.parse(urlparse(package).fragment)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2833, in parse
    req, = parse_requirements(s)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2781, in parse_requirements
    yield Requirement(line)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2790, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'/smappee'"

Kan jij hierbij helpen?


Giel

**Comment by JrtPec** [comment]
Dag Giel,

Het lijkt fout te lopen bij het parsen van je requirements. Ik weet niet hoe die parameter er moet uit zien, dus je kan best op zoek gaan naar een werkend voorbeeld en van daar verder werken. Ik merk wel 2 dingen:
- Kan het zijn dat je hier een komma vergeten bent of zo? Want nu plak je precies 2 strings tegen elkaar in een list, dat kan niet werken volgens mij.
```
    REQUIREMENTS = [
        'https://github.com/EnergyID/smappy/archive/master.zip'
        '#smappee/smappee==0.1.1']
```
- De python package heet `smappy`, niet `smappee`, dus let op voor schrijffouten.

**Comment by JrtPec** [comment]
Hey @gieljnssns, ik ga deze issue sluiten omdat het nogal buiten de scope van dit project valt. Maar als er iets is waardoor we deze package meer compatibel kunnen maken met andere projecten, laat dan zeker iets weten!
